### ISSUE TITLE
Problem with creating tables.

### ISSUE THREAD

**Issue by ryt255** [craft-soft/csbans2#1]
Hi, I had a problem today while installing CSBans, the tables were not getting created and I was receiving that error: Failed to create Database tables.

Screenshot: https://cdn.discordapp.com/attachments/1106994327470743652/1113253113797808188/image.png

PHP Version: 7.4

MySQL Version: mysql  Ver 15.1 Distrib 10.10.4-MariaDB, for debian-linux-gnu (x86_64) using readline EditLine wrapper

Also, it would be apricated if you can add support for PHP 8.x and make everything up to date.

Thank you.

**Comment by de-salvatierra** [comment]
Hello. I haven't tested this on mariadb. i will test as soon as possible

**Comment by de-salvatierra** [comment]
php 8 is supported. i tested on php 8.2

**Comment by dedimark** [comment]
same for me.

Конфигурационный файл:
Создание таблиц БД:Не удалось создать таблицы базы данных

Server version: 5.6.38 - MySQL Community Server (GPL)

Screenshot - https://prnt.sc/myjzYZ7TwJbA

Looks like csbans2 made one mysql table amx_migration

**Comment by de-salvatierra** [comment]
Errors corrected. Please download again and check.

**Comment by dedimark** [comment]
Thanks

**Comment by de-salvatierra** [comment]
> Thanks

Problem is solved?

**Comment by dedimark** [comment]
> > Thanks
> 
> Problem is solved?

yes.
