### ISSUE TITLE
Не могу изменить контент сайта

### ISSUE THREAD

**Issue by kelleboyy** [craft-soft/csbans2#11]
Хочу изменить заголовок сайта

'name' => 'пример', в main.php, не получается

В чем проблема?

**Comment by de-salvatierra** [comment]
Название сайта можно изменить в админке

**Comment by kelleboyy** [comment]
не заметил, спс большое

**Comment by kelleboyy** [comment]
![image](https://github.com/craft-soft/csbans2/assets/128936992/fa62793d-ae29-4707-9cb3-168ab6c0cf20)
После изменении названия сайта опять меняет на дефолт. Авторефрешер какой то стоит?
![image](https://github.com/craft-soft/csbans2/assets/128936992/fc13b46f-b361-4caf-8d2f-2d6c097e8f53)

Любой параметр сайта в настройке не могу изменить
